version: '3.8'

services:
  web:  #sercises  name (app)
    container_name: web   #container name
    build:
      context: . # ми вказуємо що використовуємо всі файли
      # dockerfile: Dockerfile
    container_name: go_web #container name
    image: go_main_webapp # image name
    command: /bin/sh -c "go run server.go" # run app
    env_file: .env.development # we use .env file
    ports:
      - 8080:8080  # we use 8080:8080 ports
    volumes:
      - .:/app # ми в середину докера зберігаємо свої файли. І це все лежить по path
    depends_on:  # зависимость mongo/mysql/postgress ets
      - db     # db name
  db:  #service name (db)
    container_name: db #container name
    image: mysql:latest  # image name (образ)
    env_file: .env.development  # we use .env file
    ports: # ports
      - 3306:3306 # we use 3306:3306  ports
    volumes: # we save all files
      - data-sql:/var/lib/mysql  # path where we save files

volumes: # save files
  data-sql: # service name
    driver: local  # де це все буде на локалці чи ще десь